# Site
title:              FreshiNk
bio:                'We DESIGN Your DREAMS'
description:        "Get your personalised prints with the best quality in the town. Handled with love and care"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://freshink.in
#url:                http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6

mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
facebook:           shivang.d.sharma
#github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          freshink6
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
whatsapp:           919466774803
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: http://freshink.in

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
